/**
 * pantheon-guard · jargon lexicon (fr)
 *
 * Auto-generated from pantheon-vedic-catalogue/lexicons/jargon-fr.yaml
 * by scripts/build_lexicons_for_guard.py. DO NOT EDIT DIRECTLY.
 *
 * Source description:
 *   Lexique de jargon français. Mots résistant aux règles standard de
 *
 * Catalogue anchors (for legitimacy per OPS.md):
 *   - ns-avijnatartha-5-2-9
 *   - ns-nirarthaka-5-2-8
 *
 * Token count: 121 (word + single-token derivatives, all lowercase)
 * Built: 2026-05-08T13:34Z
 */

export const JARGON_TOKENS = new Set([
  'agile',
  'agilité',
  'alignement',
  'aligner',
  'aligné',
  'b2b',
  'b2b2c',
  'b2c',
  'best-in-class',
  'bobo',
  'bobo-écolo',
  'bobos',
  'brainstormer',
  'brainstorming',
  'briefer',
  'briefing',
  'business',
  'business-model',
  'business-plan',
  'cancel',
  'cancellation',
  'canceller',
  'chakra',
  'chakral',
  'chakras',
  'changement-de-paradigme',
  'ciblage',
  'cibler',
  'ciblé',
  'coach',
  'coacher',
  'coaching',
  'coaché',
  'disrupteur',
  'disruptif',
  'disruption',
  'débriefer',
  'débriefing',
  'déploiement',
  'déployer',
  'déployé',
  'désaligné',
  'fréquence',
  'fréquences',
  'googlage',
  'googler',
  'googlé',
  'haute-fréquence',
  'hautes-vibrations',
  'holisme',
  'holistique',
  'holistiquement',
  'iaas',
  'karma',
  'karmique',
  'karmiquement',
  'kpi',
  'kpis',
  'leader',
  'leaders',
  'leadership',
  'lean',
  'lean-management',
  'lean-startup',
  'livrable',
  'livrables',
  'management',
  'manager',
  'managé',
  'managérial',
  'manifestation',
  'manifester',
  'manifesté',
  'marketer',
  'marketing',
  'marketing-mix',
  'marketé',
  'mutualisation',
  'mutualiser',
  'mutualisé',
  'mvp',
  'networker',
  'networking',
  'networké',
  'optimal',
  'optimisation',
  'optimiser',
  'optimisé',
  'paas',
  'paradigmatique',
  'paradigme',
  'pitch',
  'pitcher',
  'pitching',
  'pitché',
  'planifier',
  'planning',
  'positionnement',
  'positionner',
  'positionné',
  'roi',
  'saas',
  'scalability',
  'scalable',
  'scaler',
  'scaling',
  'scalé',
  'synergie',
  'synergique',
  'synergisme',
  'top-of-the-line',
  'vibration',
  'vibrations',
  'vibratoire',
  'woke',
  'woke-culture',
  'wokisme',
  'énergie',
  'énergie-vitale',
  'énergies-subtiles',
  'énergétique'
]);

export const META = Object.freeze({
  language: 'fr',
  schemaVersion: 1,
  status: 'v0.3.1',
  tokenCount: 121,
  catalogueAnchors: ['ns-avijnatartha-5-2-9', 'ns-nirarthaka-5-2-8'],
});
