/**
 * pantheon-guard · verdict signing (watermark layer)
 *
 * Cryptographically signs `inspect()` / `inspectConformal()` verdicts so
 * downstream consumers can prove a verdict was generated by genuine
 * pantheon-guard at a specific time, not fabricated or tampered with.
 *
 * Mechanism: HMAC-SHA-256 over a canonical JSON serialization of the
 * verdict payload, with caller-supplied secret. The signature plus a
 * timestamp and library version are added to the result.
 *
 * Threat model (see docs/SECURITY.md §4):
 *   - Catches tampering by intermediaries (proxy server, log aggregator
 *     that rewrote a verdict).
 *   - Catches fabricated verdicts not produced by the library.
 *   - Provides non-repudiable audit trail when secrets are rotated and
 *     archived.
 *   - Does *not* defend against secret compromise — that is a separate
 *     key-management problem outside this module's scope.
 *
 * The signing key is supplied by the caller. Recommendation: at least
 * 32 random bytes from a CSPRNG, stored in a secret manager (AWS KMS,
 * HashiCorp Vault, GCP Secret Manager). Do not hardcode keys.
 */

import { createHmac, timingSafeEqual } from 'node:crypto';
import { CORE_VERSION } from './constants.js';
import { inspect } from './inspect.js';

const SIGNATURE_VERSION = '1';

// ─────────────────────────────────────────────
// Canonical JSON — deterministic key ordering for signature stability.
// ─────────────────────────────────────────────

/**
 * Canonical-form JSON: object keys sorted lexicographically at every
 * level. Required so HMAC over the JSON is reproducible across runs
 * and across JS engines.
 *
 * @param {*} value
 * @returns {string}
 */
export function canonicalize(value) {
  if (value === null || typeof value !== 'object') return JSON.stringify(value);
  if (Array.isArray(value)) {
    return '[' + value.map(canonicalize).join(',') + ']';
  }
  const keys = Object.keys(value).sort();
  const parts = keys.map((k) => JSON.stringify(k) + ':' + canonicalize(value[k]));
  return '{' + parts.join(',') + '}';
}

// ─────────────────────────────────────────────
// Sign / verify
// ─────────────────────────────────────────────

/**
 * Compute the HMAC-SHA-256 signature of a payload.
 *
 * @param {*} payload — anything JSON-serializable
 * @param {string|Buffer} secret
 * @returns {string} hex-encoded signature
 */
export function signPayload(payload, secret) {
  if (!secret) throw new TypeError('signPayload requires a secret');
  const canonical = canonicalize(payload);
  return createHmac('sha256', secret).update(canonical).digest('hex');
}

/**
 * Verify an HMAC signature against a payload using timing-safe equality.
 *
 * @param {*} payload
 * @param {string} signature — hex-encoded
 * @param {string|Buffer} secret
 * @returns {boolean}
 */
export function verifyPayload(payload, signature, secret) {
  if (!secret) throw new TypeError('verifyPayload requires a secret');
  if (typeof signature !== 'string') return false;
  const expected = signPayload(payload, secret);
  if (expected.length !== signature.length) return false;
  // timingSafeEqual requires Buffer of equal length.
  return timingSafeEqual(Buffer.from(expected, 'hex'), Buffer.from(signature, 'hex'));
}

// ─────────────────────────────────────────────
// Top-level signed inspect()
// ─────────────────────────────────────────────

/**
 * Run `inspect()` and return the verdict together with a signature.
 *
 * Signed payload includes: full inspect output (sans raw text), library
 * version, signature version, and a timestamp. The `text` is hashed
 * separately and included as `text_sha256` so the signed payload does
 * not embed potentially sensitive content while still binding the
 * verdict to *that specific input*.
 *
 * @param {string} text
 * @param {Object} options — passed to inspect(), plus:
 * @param {string|Buffer} options.secret — HMAC key (required)
 * @returns {Object} signed verdict
 */
export function inspectSigned(text, options = {}) {
  const { secret, ...inspectOpts } = options;
  if (!secret) throw new TypeError('inspectSigned requires options.secret');
  const verdict = inspect(text, inspectOpts);
  const text_sha256 = createHmac('sha256', secret).update(text).digest('hex');
  const timestamp = new Date().toISOString();

  const payload = {
    ...verdict,
    text_sha256,
    timestamp,
    library: 'pantheon-guard',
    library_version: CORE_VERSION,
    signature_version: SIGNATURE_VERSION,
  };
  const signature = signPayload(payload, secret);
  return { ...payload, signature };
}

/**
 * Verify a signed verdict was produced by `inspectSigned()` with the
 * given secret and was not tampered with.
 *
 * @param {Object} signed — output of inspectSigned()
 * @param {string|Buffer} secret
 * @returns {{ valid: boolean, reason?: string }}
 */
export function verifySignedVerdict(signed, secret) {
  if (!signed || typeof signed !== 'object') {
    return { valid: false, reason: 'signed verdict must be an object' };
  }
  if (signed.library !== 'pantheon-guard') {
    return { valid: false, reason: 'unknown library identifier' };
  }
  if (signed.signature_version !== SIGNATURE_VERSION) {
    return {
      valid: false,
      reason: `unsupported signature_version=${signed.signature_version}; this build supports ${SIGNATURE_VERSION}`,
    };
  }
  const { signature, ...payload } = signed;
  if (!verifyPayload(payload, signature, secret)) {
    return { valid: false, reason: 'HMAC mismatch — payload tampered or wrong secret' };
  }
  return { valid: true };
}
